package ec.casabaca.roster.web.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-07-21T18:29:37.232-05:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "playerWebService", 
                  wsdlLocation = "http://localhost:8080/curso-inyeccion-cdi/playerWebService/playerWebService?wsdl",
                  targetNamespace = "http://soap.web.roster.casabaca.ec/") 
public class PlayerWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.web.roster.casabaca.ec/", "playerWebService");
    public final static QName PlayerWebServicePort = new QName("http://soap.web.roster.casabaca.ec/", "playerWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/curso-inyeccion-cdi/playerWebService/playerWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlayerWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/curso-inyeccion-cdi/playerWebService/playerWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlayerWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlayerWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PlayerWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PlayerWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PlayerWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PlayerWebService
     */
    @WebEndpoint(name = "playerWebServicePort")
    public PlayerWebService getPlayerWebServicePort() {
        return super.getPort(PlayerWebServicePort, PlayerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlayerWebService
     */
    @WebEndpoint(name = "playerWebServicePort")
    public PlayerWebService getPlayerWebServicePort(WebServiceFeature... features) {
        return super.getPort(PlayerWebServicePort, PlayerWebService.class, features);
    }

}
